FROM ubuntu
    RUN apt-get update -y 
    RUN apt-get install build-essential -y
    RUN apt-get install python3 -y
    RUN mkdir /fmountPoint
    RUN chmod 711 /fmountPoint
    RUN mkdir /fmountPoint/f_hiddenNum
    RUN chmod 777 /fmountPoint/f_hiddenNum
    RUN mkdir /home7
    RUN chmod 777 /home7
