FROM ubuntu
RUN apt-get update -y
RUN apt-get install -y build-essential python3 pip
RUN pip install numpy scipy pandas
RUN mkdir /fmountPoint
RUN chmod 711 /fmountPoint
RUN mkdir /fmountPoint/f_6267608047
RUN chmod 777 /fmountPoint/f_6267608047
RUN mkdir /home7
RUN chmod 777 /home7
